/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rbwjwobkmtdwxlwingdu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid2p3b2JrbXRkd3hsd2luZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzI3ODksImV4cCI6MjA3NDAwODc4OX0.gVYkHAI-xm_a9WWk2QIdrjqrfZe_rRxFALLdEXX-aQQ"